server:
  port: 9997

spring:
  application:
    name: eureka-group-server

eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: true       
    fetchRegistry: true            
    serviceUrl:
      #将自己注册到peer1的eureka注册中心上去，使得注册中心高可用
      defaultZone: http://peer1:9998/eureka/,http://peer2:9999/eureka/  