server:
  port: 9998

spring:
  application:
    name: eureka-group-server

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true       
    fetchRegistry: true            
    serviceUrl:
      defaultZone: http://peer3:9997/eureka/,http://peer2:9999/eureka/