server:
  port: 1111

spring:
  application:
    name: config-server
  profiles:
    active: native   # 开启本地配置
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:
#          - F:/spring-tool-suite-3.9.4.RELEASE-e4.7.3a-win32-x86_64/config_center_file
#          - file:/home/dz-m/dz-m-config  # linux环境

    
eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
    
  client:
    serviceUrl:
      #defaultZone: http://peer1:9998/eureka/,http://peer2:9999/eureka/,http://peer3:9997/eureka/
      defaultZone: http://localhost:8888/eureka/